---
version: "3"

services:
  main:
    image: docker.io/dmotte/dnsmasq:latest
    build: build
    restart: always
    ports: ["53:53", "53:53/udp"]
    volumes: [./dnsmasq.conf:/etc/dnsmasq.conf:ro]
