---
version: "3"

services:
  dnsmasq:
    image: dmotte/dnsmasq
    build: build
    restart: always
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
