---
version: "3"

services:
  main:
    image: docker.io/dmotte/socat:latest
    build: build
    restart: always
    ports: ["8080:8080"]
    command: TCP4-LISTEN:8080,fork,reuseaddr TCP:example.com:80
