Match User alice
    AllowTcpForwarding remote
    GatewayPorts clientspecified
    PermitListen 8001

Match User bob
    AllowTcpForwarding local
    PermitOpen 10.0.2.15:9002 10.0.2.2:9003

Match User carl
    AllowTcpForwarding yes
    GatewayPorts clientspecified
    PermitListen 8001 8002 8003
    PermitOpen 10.0.2.15:9001 10.0.2.15:9002 10.0.2.2:9003
