---
name: dockerhub-description

# This workflow requires a DOCKERHUB_PASSWORD secret to be defined in the GitHub
# repository settings.

on:
  push:
    branches: [main]
    paths:
      - dockerhub-description.md
      - .github/workflows/dockerhub-description.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOCKERHUB_USERNAME: dmotte

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        item:
          - bind
          - dnsmasq
          - socat
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.item }}
          readme-filepath: dockerhub-description.md
