---
name: main

on:
  push: # All branches and tags
  schedule:
    # Runs automatically on the 27th of every month at 04:30 UTC
    - cron: "30 04 27 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  job:
    uses: dmotte/misc/.github/workflows/cicd-with-script.yml@main
    with:
      script: >
        DOCKERHUB_USERNAME=dmotte
        CICD_SCRIPTS_DIR=$(realpath "$GITHUB_ACTION_PATH/../../scripts/cicd")
        bash cicd.sh
    secrets:
      secret01: ${{ secrets.DOCKERHUB_PASSWORD }}
